### ISSUE TITLE
[136] - The Imperial Eye - lack of Bolded Text

### ISSUE THREAD

**Issue by Wisedukk** [lenaleciel/KTB-Release-Typos-and-Errors#39] opened 2022-04-14 21:05 UTC
**The Problem:**
On pg. 136, the Emperor System "The Imperial Eye" lack Bolded Text for function game terms.
IE: Sensors, Disruptive Charge , 
range 3 instead of **Range 3**, 2 AP Damage and not **2 AP Damage**, Prone and not **Prone**, Shredded and not **Shredded**

<img width="379" alt="Screen Shot 2022-04-14 at 4 05 27 PM" src="https://user-images.githubusercontent.com/101007565/163474995-93959c3b-1c8d-4c03-9ee8-091a096e10ba.png">

**The Solution:**
**Sensors**, **Disruptive Charge**, **Range 3**, **2 AP Damage**, **Prone**, **Shredded** should all be bolded.

**The Location:**
Pg. 136, within the New Mech Chapter.

**Comment by lenaleciel** [comment] 2022-05-08 17:13
duplicate of #6, also fixed on 5/8

**Closed by lenaleciel** 2022-05-08 17:13 UTC
Labels: typo
