### ISSUE TITLE
 [132] - Sympathetic Shield not unique

### ISSUE THREAD

**Issue by Fio-Fio-Fio** [lenaleciel/KTB-Release-Typos-and-Errors#49] opened 2022-05-10 20:41 UTC
The Problem:
The White Witch system Sympathetic Shield currently does not have the unique tag, making it the only limited system in Lancer without it.
This feels like an oversight, as the Sympathetic Shield is only 1SP and you can double the amount of limited charges very easily with zero engineering investment for the cost of one system point.

The Location:
Page 132, Sympathetic Shield system

**Comment by lenaleciel** [comment] 2022-05-10 21:00
Duplicate of #48

**Closed as completed by lenaleciel** 2022-05-10 21:00 UTC
Labels: dev input needed
